import type { AchievementDef } from '../types';

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_quiz',
    name: 'First Steps',
    description: 'Complete your first quiz',
    icon: '🎯',
    condition: (s) => s.totalSessions >= 1,
  },
  {
    id: 'quiz_10',
    name: 'Getting Serious',
    description: 'Complete 10 quizzes',
    icon: '📚',
    condition: (s) => s.totalSessions >= 10,
  },
  {
    id: 'quiz_50',
    name: 'Dedicated Learner',
    description: 'Complete 50 quizzes',
    icon: '🏆',
    condition: (s) => s.totalSessions >= 50,
  },
  {
    id: 'questions_100',
    name: 'Century',
    description: 'Answer 100 questions',
    icon: '💯',
    condition: (s) => s.totalQuestions >= 100,
  },
  {
    id: 'questions_500',
    name: 'Knowledge Machine',
    description: 'Answer 500 questions',
    icon: '🤖',
    condition: (s) => s.totalQuestions >= 500,
  },
  {
    id: 'questions_1000',
    name: 'Unstoppable',
    description: 'Answer 1000 questions',
    icon: '🔥',
    condition: (s) => s.totalQuestions >= 1000,
  },
  {
    id: 'perfect_score',
    name: 'Flawless',
    description: 'Get 100% on a quiz',
    icon: '⭐',
    condition: (s) => s.perfectScores >= 1,
  },
  {
    id: 'perfect_5',
    name: 'Perfectionist',
    description: 'Get 100% on 5 quizzes',
    icon: '🌟',
    condition: (s) => s.perfectScores >= 5,
  },
  {
    id: 'streak_3',
    name: 'On Fire',
    description: '3-day practice streak',
    icon: '🔥',
    condition: (s) => s.streak >= 3,
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: '7-day practice streak',
    icon: '⚔️',
    condition: (s) => s.streak >= 7,
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    description: '30-day practice streak',
    icon: '👑',
    condition: (s) => s.streak >= 30,
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Answer a question in under 3 seconds',
    icon: '⚡',
    condition: (s) => s.fastestAnswer !== null && s.fastestAnswer < 3,
  },
  {
    id: 'polyglot',
    name: 'Polyglot',
    description: 'Practice 5 different subjects',
    icon: '🌍',
    condition: (s) => s.subjects >= 5,
  },
  {
    id: 'accuracy_80',
    name: 'Sharpshooter',
    description: 'Achieve 80%+ accuracy across all sessions',
    icon: '🎯',
    condition: (s) => s.totalQuestions >= 20 && (s.totalCorrect / s.totalQuestions) >= 0.8,
  },
  {
    id: 'accuracy_95',
    name: 'Genius',
    description: 'Achieve 95%+ accuracy across all sessions',
    icon: '🧠',
    condition: (s) => s.totalQuestions >= 20 && (s.totalCorrect / s.totalQuestions) >= 0.95,
  },
  {
    id: 'time_1h',
    name: 'Committed',
    description: 'Spend over 1 hour practicing',
    icon: '⏰',
    condition: (s) => s.timeSpent >= 3600,
  },
  {
    id: 'time_10h',
    name: 'Dedicated',
    description: 'Spend over 10 hours practicing',
    icon: '📖',
    condition: (s) => s.timeSpent >= 36000,
  },
];
